name: Unit Tests
run-name: Unit Tests on pull request {{ github.event.pull_request.title }} opened by {{ github.actor }}
on:
  pull_request:
    branches:
      - main
      - v**
    paths:
      - 'src/**'
jobs:
  call-unit-tests-workflow:
    uses: ./.github/workflows/unit-tests.yml
